from Diff import * 
import snap7

def PLC_Wrirte(db):

    global G_Var
    snap7.util.set_int(db,G_Var['Robot'][0]['ID']['Address'],G_Var['Robot'][0]['ID']['Value'])
    snap7.util.set_bool(db,G_Var['Robot'][0]['Error']['Address'],G_Var['Robot'][0]['Error']['Start_bit'],bool(G_Var['Robot'][0]['Error']['Value']))
    snap7.util.set_bool(db,G_Var['Robot'][0]['Busy']['Address'],G_Var['Robot'][0]['Busy']['Start_bit'],bool(G_Var['Robot'][0]['Busy']['Value']))
    snap7.util.set_bool(db,G_Var['Robot'][0]['Done']['Address'],G_Var['Robot'][0]['Done']['Start_bit'],bool(G_Var['Robot'][0]['Done']['Value']))
    snap7.util.set_bool(db,G_Var['Robot'][0]['Gripper_Indicator']['Address'],G_Var['Robot'][0]['Gripper_Indicator']['Start_bit'],bool(G_Var['Robot'][0]['Gripper_Indicator']['Value']))
    snap7.util.set_int(db,G_Var['Robot'][0]['Robot_Position']['Address'],G_Var['Robot'][0]['Robot_Position']['Value'])
    snap7.util.set_int(db,G_Var['Robot'][0]['Motors'][0]['ID']['Address'],G_Var['Robot'][0]['Motors'][0]['ID']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][0]['Position']['Address'],G_Var['Robot'][0]['Motors'][0]['Position']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][0]['Velocity']['Address'],G_Var['Robot'][0]['Motors'][0]['Velocity']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][0]['Torque']['Address'],G_Var['Robot'][0]['Motors'][0]['Torque']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][0]['Temp']['Address'],G_Var['Robot'][0]['Motors'][0]['Temp']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][0]['Volt']['Address'],G_Var['Robot'][0]['Motors'][0]['Volt']['Value'])
    snap7.util.set_int(db,G_Var['Robot'][0]['Motors'][1]['ID']['Address'],G_Var['Robot'][0]['Motors'][1]['ID']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][1]['Position']['Address'],G_Var['Robot'][0]['Motors'][1]['Position']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][1]['Velocity']['Address'],G_Var['Robot'][0]['Motors'][1]['Velocity']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][1]['Torque']['Address'],G_Var['Robot'][0]['Motors'][1]['Torque']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][1]['Temp']['Address'],G_Var['Robot'][0]['Motors'][1]['Temp']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][1]['Volt']['Address'],G_Var['Robot'][0]['Motors'][1]['Volt']['Value'])
    snap7.util.set_int(db,G_Var['Robot'][0]['Motors'][2]['ID']['Address'],G_Var['Robot'][0]['Motors'][2]['ID']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][2]['Position']['Address'],G_Var['Robot'][0]['Motors'][2]['Position']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][2]['Velocity']['Address'],G_Var['Robot'][0]['Motors'][2]['Velocity']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][2]['Torque']['Address'],G_Var['Robot'][0]['Motors'][2]['Torque']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][2]['Temp']['Address'],G_Var['Robot'][0]['Motors'][2]['Temp']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][0]['Motors'][2]['Volt']['Address'],G_Var['Robot'][0]['Motors'][2]['Volt']['Value'])
    snap7.util.set_int(db,G_Var['Robot'][1]['ID']['Address'],G_Var['Robot'][1]['ID']['Value'])
    snap7.util.set_bool(db,G_Var['Robot'][1]['Error']['Address'],G_Var['Robot'][1]['Error']['Start_bit'],bool(G_Var['Robot'][1]['Error']['Value']))
    snap7.util.set_bool(db,G_Var['Robot'][1]['Busy']['Address'],G_Var['Robot'][1]['Busy']['Start_bit'],bool(G_Var['Robot'][1]['Busy']['Value']))
    snap7.util.set_bool(db,G_Var['Robot'][1]['Done']['Address'],G_Var['Robot'][1]['Done']['Start_bit'],bool(G_Var['Robot'][1]['Done']['Value']))
    snap7.util.set_bool(db,G_Var['Robot'][1]['Gripper_Indicator']['Address'],G_Var['Robot'][1]['Gripper_Indicator']['Start_bit'],bool(G_Var['Robot'][1]['Gripper_Indicator']['Value']))
    snap7.util.set_int(db,G_Var['Robot'][1]['Robot_Position']['Address'],G_Var['Robot'][1]['Robot_Position']['Value'])
    snap7.util.set_int(db,G_Var['Robot'][1]['Motors'][0]['ID']['Address'],G_Var['Robot'][1]['Motors'][0]['ID']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][0]['Position']['Address'],G_Var['Robot'][1]['Motors'][0]['Position']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][0]['Velocity']['Address'],G_Var['Robot'][1]['Motors'][0]['Velocity']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][0]['Torque']['Address'],G_Var['Robot'][1]['Motors'][0]['Torque']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][0]['Temp']['Address'],G_Var['Robot'][1]['Motors'][0]['Temp']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][0]['Volt']['Address'],G_Var['Robot'][1]['Motors'][0]['Volt']['Value'])
    snap7.util.set_int(db,G_Var['Robot'][1]['Motors'][1]['ID']['Address'],G_Var['Robot'][1]['Motors'][1]['ID']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][1]['Position']['Address'],G_Var['Robot'][1]['Motors'][1]['Position']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][1]['Velocity']['Address'],G_Var['Robot'][1]['Motors'][1]['Velocity']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][1]['Torque']['Address'],G_Var['Robot'][1]['Motors'][1]['Torque']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][1]['Temp']['Address'],G_Var['Robot'][1]['Motors'][1]['Temp']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][1]['Volt']['Address'],G_Var['Robot'][1]['Motors'][1]['Volt']['Value'])
    snap7.util.set_int(db,G_Var['Robot'][1]['Motors'][2]['ID']['Address'],G_Var['Robot'][1]['Motors'][2]['ID']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][2]['Position']['Address'],G_Var['Robot'][1]['Motors'][2]['Position']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][2]['Velocity']['Address'],G_Var['Robot'][1]['Motors'][2]['Velocity']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][2]['Torque']['Address'],G_Var['Robot'][1]['Motors'][2]['Torque']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][2]['Temp']['Address'],G_Var['Robot'][1]['Motors'][2]['Temp']['Value'])
    snap7.util.set_real(db,G_Var['Robot'][1]['Motors'][2]['Volt']['Address'],G_Var['Robot'][1]['Motors'][2]['Volt']['Value'])
    snap7.util.set_bool(db,G_Var['Raspberry'][0]['Error']['Address'],G_Var['Raspberry'][0]['Error']['Start_bit'],bool(G_Var['Raspberry'][0]['Error']['Value']))
    snap7.util.set_bool(db,G_Var['Raspberry'][0]['Ready']['Address'],G_Var['Raspberry'][0]['Ready']['Start_bit'],bool(G_Var['Raspberry'][0]['Ready']['Value']))
    snap7.util.set_byte(db,G_Var['Raspberry'][0]['IP'][0]['Address'],G_Var['Raspberry'][0]['IP'][0]['Value'])
    snap7.util.set_byte(db,G_Var['Raspberry'][0]['IP'][1]['Address'],G_Var['Raspberry'][0]['IP'][1]['Value'])
    snap7.util.set_byte(db,G_Var['Raspberry'][0]['IP'][2]['Address'],G_Var['Raspberry'][0]['IP'][2]['Value'])
    snap7.util.set_byte(db,G_Var['Raspberry'][0]['IP'][3]['Address'],G_Var['Raspberry'][0]['IP'][3]['Value'])
    snap7.util.set_string(db,G_Var['IoT'][0]['Name']['Address'],G_Var['IoT'][0]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['IoT'][0]['Connect']['Address'],G_Var['IoT'][0]['Connect']['Start_bit'],bool(G_Var['IoT'][0]['Connect']['Value']))
    snap7.util.set_byte(db,G_Var['HMI'][1]['IP'][0]['Address'],G_Var['HMI'][1]['IP'][0]['Value'])
    snap7.util.set_byte(db,G_Var['HMI'][1]['IP'][1]['Address'],G_Var['HMI'][1]['IP'][1]['Value'])
    snap7.util.set_byte(db,G_Var['HMI'][1]['IP'][2]['Address'],G_Var['HMI'][1]['IP'][2]['Value'])
    snap7.util.set_byte(db,G_Var['HMI'][1]['IP'][3]['Address'],G_Var['HMI'][1]['IP'][3]['Value'])
    snap7.util.set_bool(db,G_Var['HMI'][1]['Connect']['Address'],G_Var['HMI'][1]['Connect']['Start_bit'],bool(G_Var['HMI'][1]['Connect']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][0]['Name']['Address'],G_Var['HMI'][1]['Buttons'][0]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][0]['Val']['Address'],G_Var['HMI'][1]['Buttons'][0]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][0]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][1]['Name']['Address'],G_Var['HMI'][1]['Buttons'][1]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][1]['Val']['Address'],G_Var['HMI'][1]['Buttons'][1]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][1]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][2]['Name']['Address'],G_Var['HMI'][1]['Buttons'][2]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][2]['Val']['Address'],G_Var['HMI'][1]['Buttons'][2]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][2]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][3]['Name']['Address'],G_Var['HMI'][1]['Buttons'][3]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][3]['Val']['Address'],G_Var['HMI'][1]['Buttons'][3]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][3]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][4]['Name']['Address'],G_Var['HMI'][1]['Buttons'][4]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][4]['Val']['Address'],G_Var['HMI'][1]['Buttons'][4]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][4]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][5]['Name']['Address'],G_Var['HMI'][1]['Buttons'][5]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][5]['Val']['Address'],G_Var['HMI'][1]['Buttons'][5]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][5]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][6]['Name']['Address'],G_Var['HMI'][1]['Buttons'][6]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][6]['Val']['Address'],G_Var['HMI'][1]['Buttons'][6]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][6]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][7]['Name']['Address'],G_Var['HMI'][1]['Buttons'][7]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][7]['Val']['Address'],G_Var['HMI'][1]['Buttons'][7]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][7]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][8]['Name']['Address'],G_Var['HMI'][1]['Buttons'][8]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][8]['Val']['Address'],G_Var['HMI'][1]['Buttons'][8]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][8]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][9]['Name']['Address'],G_Var['HMI'][1]['Buttons'][9]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][9]['Val']['Address'],G_Var['HMI'][1]['Buttons'][9]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][9]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][10]['Name']['Address'],G_Var['HMI'][1]['Buttons'][10]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][10]['Val']['Address'],G_Var['HMI'][1]['Buttons'][10]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][10]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][11]['Name']['Address'],G_Var['HMI'][1]['Buttons'][11]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][11]['Val']['Address'],G_Var['HMI'][1]['Buttons'][11]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][11]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][12]['Name']['Address'],G_Var['HMI'][1]['Buttons'][12]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][12]['Val']['Address'],G_Var['HMI'][1]['Buttons'][12]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][12]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][13]['Name']['Address'],G_Var['HMI'][1]['Buttons'][13]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][13]['Val']['Address'],G_Var['HMI'][1]['Buttons'][13]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][13]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][14]['Name']['Address'],G_Var['HMI'][1]['Buttons'][14]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][14]['Val']['Address'],G_Var['HMI'][1]['Buttons'][14]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][14]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][15]['Name']['Address'],G_Var['HMI'][1]['Buttons'][15]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][15]['Val']['Address'],G_Var['HMI'][1]['Buttons'][15]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][15]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][16]['Name']['Address'],G_Var['HMI'][1]['Buttons'][16]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][16]['Val']['Address'],G_Var['HMI'][1]['Buttons'][16]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][16]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][17]['Name']['Address'],G_Var['HMI'][1]['Buttons'][17]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][17]['Val']['Address'],G_Var['HMI'][1]['Buttons'][17]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][17]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][18]['Name']['Address'],G_Var['HMI'][1]['Buttons'][18]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][18]['Val']['Address'],G_Var['HMI'][1]['Buttons'][18]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][18]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][19]['Name']['Address'],G_Var['HMI'][1]['Buttons'][19]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][19]['Val']['Address'],G_Var['HMI'][1]['Buttons'][19]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][19]['Val']['Value']))
    snap7.util.set_string(db,G_Var['HMI'][1]['Buttons'][20]['Name']['Address'],G_Var['HMI'][1]['Buttons'][20]['Name']['Value'],200)
    snap7.util.set_bool(db,G_Var['HMI'][1]['Buttons'][20]['Val']['Address'],G_Var['HMI'][1]['Buttons'][20]['Val']['Start_bit'],bool(G_Var['HMI'][1]['Buttons'][20]['Val']['Value']))
    
    return db

def PLC_Read(db):

    global G_Var
    G_Var['Robot'][0]['Start']['Value'] = snap7.util.get_bool(db,G_Var['Robot'][0]['Start']['Address'],G_Var['Robot'][0]['Start']['Start_bit'])
    G_Var['Robot'][0]['Gripper_control']['Value'] = snap7.util.get_bool(db,G_Var['Robot'][0]['Gripper_control']['Address'],G_Var['Robot'][0]['Gripper_control']['Start_bit'])
    G_Var['Robot'][1]['Start']['Value'] = snap7.util.get_bool(db,G_Var['Robot'][1]['Start']['Address'],G_Var['Robot'][1]['Start']['Start_bit'])
    G_Var['Robot'][1]['Gripper_control']['Value'] = snap7.util.get_bool(db,G_Var['Robot'][1]['Gripper_control']['Address'],G_Var['Robot'][1]['Gripper_control']['Start_bit'])
    G_Var['PLC'][0]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Name']['Address'],200)
    G_Var['PLC'][0]['IP'][0]['Value'] = snap7.util.get_byte(db,G_Var['PLC'][0]['IP'][0]['Address'])
    G_Var['PLC'][0]['IP'][1]['Value'] = snap7.util.get_byte(db,G_Var['PLC'][0]['IP'][1]['Address'])
    G_Var['PLC'][0]['IP'][2]['Value'] = snap7.util.get_byte(db,G_Var['PLC'][0]['IP'][2]['Address'])
    G_Var['PLC'][0]['IP'][3]['Value'] = snap7.util.get_byte(db,G_Var['PLC'][0]['IP'][3]['Address'])
    G_Var['PLC'][0]['Connect']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Connect']['Address'],G_Var['PLC'][0]['Connect']['Start_bit'])
    G_Var['PLC'][0]['Automatic']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Automatic']['Address'],G_Var['PLC'][0]['Automatic']['Start_bit'])
    G_Var['PLC'][0]['IoT_Allow']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['IoT_Allow']['Address'],G_Var['PLC'][0]['IoT_Allow']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][0]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][0]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][0]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][0]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][0]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][1]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][1]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][1]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][1]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][1]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][2]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][2]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][2]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][2]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][2]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][3]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][3]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][3]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][3]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][3]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][4]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][4]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][4]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][4]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][4]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][5]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][5]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][5]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][5]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][5]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][6]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][6]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][6]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][6]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][6]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][7]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][7]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][7]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][7]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][7]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][8]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][8]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][8]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][8]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][8]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][9]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][9]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][9]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][9]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][9]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][10]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][10]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][10]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][10]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][10]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][11]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][11]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][11]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][11]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][11]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][12]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][12]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][12]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][12]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][12]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Inputs'][13]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Inputs'][13]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Inputs'][13]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Inputs'][13]['Value']['Address'],G_Var['PLC'][0]['Digital_Inputs'][13]['Value']['Start_bit'])
    G_Var['PLC'][0]['Analog_Inputs'][0]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Analog_Inputs'][0]['Name']['Address'],200)
    G_Var['PLC'][0]['Analog_Inputs'][0]['Value']['Value'] = snap7.util.get_real(db,G_Var['PLC'][0]['Analog_Inputs'][0]['Value']['Address'])
    G_Var['PLC'][0]['Analog_Inputs'][0]['Index']['Value'] = snap7.util.get_int(db,G_Var['PLC'][0]['Analog_Inputs'][0]['Index']['Address'])
    G_Var['PLC'][0]['Analog_Inputs'][1]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Analog_Inputs'][1]['Name']['Address'],200)
    G_Var['PLC'][0]['Analog_Inputs'][1]['Value']['Value'] = snap7.util.get_real(db,G_Var['PLC'][0]['Analog_Inputs'][1]['Value']['Address'])
    G_Var['PLC'][0]['Analog_Inputs'][1]['Index']['Value'] = snap7.util.get_int(db,G_Var['PLC'][0]['Analog_Inputs'][1]['Index']['Address'])
    G_Var['PLC'][0]['Digital_Outputs'][0]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Outputs'][0]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Outputs'][0]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][0]['Value']['Address'],G_Var['PLC'][0]['Digital_Outputs'][0]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][0]['Direction']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][0]['Direction']['Address'],G_Var['PLC'][0]['Digital_Outputs'][0]['Direction']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][1]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Outputs'][1]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Outputs'][1]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][1]['Value']['Address'],G_Var['PLC'][0]['Digital_Outputs'][1]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][1]['Direction']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][1]['Direction']['Address'],G_Var['PLC'][0]['Digital_Outputs'][1]['Direction']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][2]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Outputs'][2]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Outputs'][2]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][2]['Value']['Address'],G_Var['PLC'][0]['Digital_Outputs'][2]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][2]['Direction']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][2]['Direction']['Address'],G_Var['PLC'][0]['Digital_Outputs'][2]['Direction']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][3]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Outputs'][3]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Outputs'][3]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][3]['Value']['Address'],G_Var['PLC'][0]['Digital_Outputs'][3]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][3]['Direction']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][3]['Direction']['Address'],G_Var['PLC'][0]['Digital_Outputs'][3]['Direction']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][4]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Outputs'][4]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Outputs'][4]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][4]['Value']['Address'],G_Var['PLC'][0]['Digital_Outputs'][4]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][4]['Direction']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][4]['Direction']['Address'],G_Var['PLC'][0]['Digital_Outputs'][4]['Direction']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][5]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Outputs'][5]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Outputs'][5]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][5]['Value']['Address'],G_Var['PLC'][0]['Digital_Outputs'][5]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][5]['Direction']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][5]['Direction']['Address'],G_Var['PLC'][0]['Digital_Outputs'][5]['Direction']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][6]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Outputs'][6]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Outputs'][6]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][6]['Value']['Address'],G_Var['PLC'][0]['Digital_Outputs'][6]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][6]['Direction']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][6]['Direction']['Address'],G_Var['PLC'][0]['Digital_Outputs'][6]['Direction']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][7]['Name']['Value'] = snap7.util.get_string(db,G_Var['PLC'][0]['Digital_Outputs'][7]['Name']['Address'],200)
    G_Var['PLC'][0]['Digital_Outputs'][7]['Value']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][7]['Value']['Address'],G_Var['PLC'][0]['Digital_Outputs'][7]['Value']['Start_bit'])
    G_Var['PLC'][0]['Digital_Outputs'][7]['Direction']['Value'] = snap7.util.get_bool(db,G_Var['PLC'][0]['Digital_Outputs'][7]['Direction']['Address'],G_Var['PLC'][0]['Digital_Outputs'][7]['Direction']['Start_bit'])
    G_Var['HMI'][0]['IP'][0]['Value'] = snap7.util.get_byte(db,G_Var['HMI'][0]['IP'][0]['Address'])
    G_Var['HMI'][0]['IP'][1]['Value'] = snap7.util.get_byte(db,G_Var['HMI'][0]['IP'][1]['Address'])
    G_Var['HMI'][0]['IP'][2]['Value'] = snap7.util.get_byte(db,G_Var['HMI'][0]['IP'][2]['Address'])
    G_Var['HMI'][0]['IP'][3]['Value'] = snap7.util.get_byte(db,G_Var['HMI'][0]['IP'][3]['Address'])
    G_Var['HMI'][0]['Connect']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Connect']['Address'],G_Var['HMI'][0]['Connect']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][0]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][0]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][0]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][0]['Val']['Address'],G_Var['HMI'][0]['Buttons'][0]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][1]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][1]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][1]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][1]['Val']['Address'],G_Var['HMI'][0]['Buttons'][1]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][2]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][2]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][2]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][2]['Val']['Address'],G_Var['HMI'][0]['Buttons'][2]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][3]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][3]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][3]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][3]['Val']['Address'],G_Var['HMI'][0]['Buttons'][3]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][4]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][4]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][4]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][4]['Val']['Address'],G_Var['HMI'][0]['Buttons'][4]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][5]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][5]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][5]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][5]['Val']['Address'],G_Var['HMI'][0]['Buttons'][5]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][6]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][6]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][6]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][6]['Val']['Address'],G_Var['HMI'][0]['Buttons'][6]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][7]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][7]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][7]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][7]['Val']['Address'],G_Var['HMI'][0]['Buttons'][7]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][8]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][8]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][8]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][8]['Val']['Address'],G_Var['HMI'][0]['Buttons'][8]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][9]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][9]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][9]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][9]['Val']['Address'],G_Var['HMI'][0]['Buttons'][9]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][10]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][10]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][10]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][10]['Val']['Address'],G_Var['HMI'][0]['Buttons'][10]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][11]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][11]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][11]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][11]['Val']['Address'],G_Var['HMI'][0]['Buttons'][11]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][12]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][12]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][12]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][12]['Val']['Address'],G_Var['HMI'][0]['Buttons'][12]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][13]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][13]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][13]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][13]['Val']['Address'],G_Var['HMI'][0]['Buttons'][13]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][14]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][14]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][14]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][14]['Val']['Address'],G_Var['HMI'][0]['Buttons'][14]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][15]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][15]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][15]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][15]['Val']['Address'],G_Var['HMI'][0]['Buttons'][15]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][16]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][16]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][16]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][16]['Val']['Address'],G_Var['HMI'][0]['Buttons'][16]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][17]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][17]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][17]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][17]['Val']['Address'],G_Var['HMI'][0]['Buttons'][17]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][18]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][18]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][18]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][18]['Val']['Address'],G_Var['HMI'][0]['Buttons'][18]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][19]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][19]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][19]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][19]['Val']['Address'],G_Var['HMI'][0]['Buttons'][19]['Val']['Start_bit'])
    G_Var['HMI'][0]['Buttons'][20]['Name']['Value'] = snap7.util.get_string(db,G_Var['HMI'][0]['Buttons'][20]['Name']['Address'],200)
    G_Var['HMI'][0]['Buttons'][20]['Val']['Value'] = snap7.util.get_bool(db,G_Var['HMI'][0]['Buttons'][20]['Val']['Address'],G_Var['HMI'][0]['Buttons'][20]['Val']['Start_bit'])